# Generated by Django 5.0.6 on 2024-06-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collexn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollexnWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collexn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collexn.collexn')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collexn.wine')),
            ],
        ),
        migrations.AlterField(
            model_name='collexn',
            name='wines',
            field=models.ManyToManyField(blank=True, through='collexn.CollexnWine', to='collexn.wine'),
        ),
    ]
